version: '3.7'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis/data
    networks:
      - backend

  backend:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - backend

volumes:
  redis:

networks:
  backend: